import { motion } from 'framer-motion'

export default function Hero() {
  return (
    <section className="mx-auto max-w-3xl px-5 pb-10 pt-16 text-center sm:pt-24">
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-base-border bg-white/[0.03] px-3.5 py-1.5 font-mono text-[11px] text-ink-500"
      >
        <span className="h-1.5 w-1.5 rounded-full bg-accent-violet" />
        Base Qwen model vs. LoRA fine-tune
      </motion.div>

      <motion.h1
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.55, delay: 0.05 }}
        className="font-display text-4xl font-bold leading-[1.1] tracking-tight text-ink-100 sm:text-5xl"
      >
        Compare <span className="text-gradient">Base Model</span>
        <br className="hidden sm:block" /> vs Fine-Tuned <span className="text-gradient">LoRA</span>
      </motion.h1>

      <motion.p
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.55, delay: 0.12 }}
        className="mx-auto mt-5 max-w-xl text-balance text-[15px] leading-relaxed text-ink-500 sm:text-base"
      >
        See how LoRA changes writing style while preserving the meaning generated by the base model.
      </motion.p>
    </section>
  )
}
